apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: hiransanjeewa/getting-started 
        env:
         - name: DB-PORT
           valueFrom:
            configMapKeyRef:
             name: configmap-test
             key: db-port
        ports:
        - containerPort: 8080

